package Opening;

import AddingPanels.Add_Appointment;
import AddingPanels.Add_HealthHistory;
import AddingPanels.Add_Students;
import Opening.LogIn_SignUp;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jay Aguirre Alfeche
 */
public class Clinic_Appointment_System extends javax.swing.JFrame {

    private Clinic_Appointment_System dashboard;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Clinic_Appointment_System.class.getName());

    private CardLayout card;

    public void addAppointmentToTable(
        int id,
        String student,
        String date,
        String time,
        String purpose,
        String status,
        String handledBy) {

        DefaultTableModel model
            = (DefaultTableModel) TableAppoint.getModel();

        model.addRow(new Object[]{
            id,
            student,
            date,
            time,
            purpose,
            status,
            handledBy
        });
    }

    public Clinic_Appointment_System() {
        initComponents();
        card = (CardLayout) pnlContent.getLayout();

        this.setLocationRelativeTo(null);

        this.setResizable(false);
        this.setMinimumSize(new java.awt.Dimension(809, 622));
        this.setMaximumSize(new java.awt.Dimension(809, 622));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnDashbd = new javax.swing.JButton();
        btnAppoint = new javax.swing.JButton();
        btnStuds = new javax.swing.JButton();
        btnHR = new javax.swing.JButton();
        btnOUT = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlDashbd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAppt = new javax.swing.JButton();
        btnAddStud = new javax.swing.JButton();
        btnHRs = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlAppoint = new javax.swing.JPanel();
        btnAddAppoint = new javax.swing.JButton();
        btnEditApp = new javax.swing.JButton();
        btnDeleteApp = new javax.swing.JButton();
        btnCStsApp = new javax.swing.JButton();
        btnVDtlsApp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAppoint = new javax.swing.JTable();
        pnlStuds = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        btnProf = new javax.swing.JButton();
        btnEditStud = new javax.swing.JButton();
        btnDeleteStud = new javax.swing.JButton();
        btnBookApp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pnlHR = new javax.swing.JPanel();
        btnAddHR = new javax.swing.JButton();
        btnVWHR = new javax.swing.JButton();
        btnDeleteHR = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(10, 35, 66));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("CLINIC APPOINTMENT AND STUDENT MONITORING SYSTEM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(1, 79, 134));

        btnDashbd.setBackground(new java.awt.Color(10, 35, 66));
        btnDashbd.setForeground(new java.awt.Color(255, 255, 255));
        btnDashbd.setText("DASHBOARD");
        btnDashbd.setBorderPainted(false);
        btnDashbd.setFocusPainted(false);
        btnDashbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashbdActionPerformed(evt);
            }
        });

        btnAppoint.setBackground(new java.awt.Color(10, 35, 66));
        btnAppoint.setText("APPOINTMENTS");
        btnAppoint.setAutoscrolls(true);
        btnAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointActionPerformed(evt);
            }
        });

        btnStuds.setBackground(new java.awt.Color(10, 35, 66));
        btnStuds.setText("STUDENT RECORDS ");
        btnStuds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudsActionPerformed(evt);
            }
        });

        btnHR.setBackground(new java.awt.Color(214, 40, 40));
        btnHR.setText("🩺 HEALTH RECORDS");
        btnHR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHRActionPerformed(evt);
            }
        });

        btnOUT.setText("LOG OUT");
        btnOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStuds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAppoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDashbd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOUT)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnDashbd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnStuds, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnHR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(btnOUT)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pnlContent.setBackground(new java.awt.Color(153, 153, 153));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlDashbd.setBackground(new java.awt.Color(225, 245, 254));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("QUICK ACTIONS");

        btnAppt.setBackground(new java.awt.Color(0, 96, 225));
        btnAppt.setText("APPOINTMENT");
        btnAppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApptActionPerformed(evt);
            }
        });

        btnAddStud.setBackground(new java.awt.Color(56, 142, 60));
        btnAddStud.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStud.setText("ADD STUDENT");
        btnAddStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudActionPerformed(evt);
            }
        });

        btnHRs.setBackground(new java.awt.Color(153, 0, 0));
        btnHRs.setText("HEALTH RECORDS");
        btnHRs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHRsActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(70, 130, 180));
        btnSearch.setText("SEARCH STUDENT");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("\"CLINIC'S APPOINTMENT\"");

        javax.swing.GroupLayout pnlDashbdLayout = new javax.swing.GroupLayout(pnlDashbd);
        pnlDashbd.setLayout(pnlDashbdLayout);
        pnlDashbdLayout.setHorizontalGroup(
            pnlDashbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashbdLayout.createSequentialGroup()
                .addGroup(pnlDashbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashbdLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(pnlDashbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDashbdLayout.createSequentialGroup()
                                .addGroup(pnlDashbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAppt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHRs, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDashbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddStud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))))
                    .addGroup(pnlDashbdLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlDashbdLayout.setVerticalGroup(
            pnlDashbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashbdLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDashbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAppt, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(btnAddStud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDashbdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHRs, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pnlContent.add(pnlDashbd, "Dashbd");

        pnlAppoint.setBackground(new java.awt.Color(225, 245, 254));

        btnAddAppoint.setBackground(new java.awt.Color(56, 142, 60));
        btnAddAppoint.setText("ADD APPOINTMENT");
        btnAddAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAppointActionPerformed(evt);
            }
        });

        btnEditApp.setBackground(new java.awt.Color(0, 7, 136));
        btnEditApp.setText("Edit");
        btnEditApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAppActionPerformed(evt);
            }
        });

        btnDeleteApp.setBackground(new java.awt.Color(183, 28, 28));
        btnDeleteApp.setText("Delete");
        btnDeleteApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAppActionPerformed(evt);
            }
        });

        btnCStsApp.setBackground(new java.awt.Color(0, 84, 34));
        btnCStsApp.setText("Change Status");
        btnCStsApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCStsAppActionPerformed(evt);
            }
        });

        btnVDtlsApp.setBackground(new java.awt.Color(0, 102, 102));
        btnVDtlsApp.setText("View Details");
        btnVDtlsApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVDtlsAppActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("\"TABLE OF ALL APPOINTMENTS\"");

        TableAppoint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appt ID", "Student Name", "Date", "Time", "Purpose", "Status", "Handled By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableAppoint);

        javax.swing.GroupLayout pnlAppointLayout = new javax.swing.GroupLayout(pnlAppoint);
        pnlAppoint.setLayout(pnlAppointLayout);
        pnlAppointLayout.setHorizontalGroup(
            pnlAppointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlAppointLayout.createSequentialGroup()
                .addGroup(pnlAppointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAppointLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnEditApp)
                        .addGap(5, 5, 5)
                        .addComponent(btnDeleteApp, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnCStsApp)
                        .addGap(5, 5, 5)
                        .addComponent(btnVDtlsApp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAppointLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAppointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addGroup(pnlAppointLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAddAppoint))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAppointLayout.setVerticalGroup(
            pnlAppointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAppointLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(pnlAppointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAppointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditApp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteApp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCStsApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVDtlsApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlContent.add(pnlAppoint, "Appoint");

        pnlStuds.setBackground(new java.awt.Color(225, 245, 254));

        btnAddStudent.setBackground(new java.awt.Color(11, 144, 59));
        btnAddStudent.setText("ADD STUDENT");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnProf.setBackground(new java.awt.Color(204, 204, 204));
        btnProf.setForeground(new java.awt.Color(0, 8, 12));
        btnProf.setText("Profile");
        btnProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfActionPerformed(evt);
            }
        });

        btnEditStud.setBackground(new java.awt.Color(0, 96, 225));
        btnEditStud.setText("Edit");
        btnEditStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStudActionPerformed(evt);
            }
        });

        btnDeleteStud.setBackground(new java.awt.Color(183, 28, 28));
        btnDeleteStud.setText("Delete");
        btnDeleteStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudActionPerformed(evt);
            }
        });

        btnBookApp.setText("Book Appt");
        btnBookApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAppActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("\"TABLE OF ALL STUDENT'S\"");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Course", "Year", "Email", "Blood Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout pnlStudsLayout = new javax.swing.GroupLayout(pnlStuds);
        pnlStuds.setLayout(pnlStudsLayout);
        pnlStudsLayout.setHorizontalGroup(
            pnlStudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStudsLayout.createSequentialGroup()
                        .addComponent(btnProf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditStud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteStud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookApp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlStudsLayout.setVerticalGroup(
            pnlStudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStudsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditStud, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteStud, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookApp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlContent.add(pnlStuds, "Studs");

        pnlHR.setBackground(new java.awt.Color(225, 245, 254));

        btnAddHR.setBackground(new java.awt.Color(11, 144, 59));
        btnAddHR.setText("ADD HEALTH RECORDS");
        btnAddHR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHRActionPerformed(evt);
            }
        });

        btnVWHR.setText("View Full Record");
        btnVWHR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVWHRActionPerformed(evt);
            }
        });

        btnDeleteHR.setBackground(new java.awt.Color(183, 28, 28));
        btnDeleteHR.setText("Delete");
        btnDeleteHR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHRActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Student", "Date", "Visit Type", "Chief Complain", "Diagnosis", "BP", "Temp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("\"TABLE OF ALL HEALTH HISTORY\"");

        javax.swing.GroupLayout pnlHRLayout = new javax.swing.GroupLayout(pnlHR);
        pnlHR.setLayout(pnlHRLayout);
        pnlHRLayout.setHorizontalGroup(
            pnlHRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddHR))
            .addGroup(pnlHRLayout.createSequentialGroup()
                .addGroup(pnlHRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHRLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlHRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHRLayout.createSequentialGroup()
                                .addComponent(btnVWHR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteHR)
                                .addGap(0, 356, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)))
                    .addGroup(pnlHRLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHRLayout.setVerticalGroup(
            pnlHRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddHR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pnlHRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVWHR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteHR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlContent.add(pnlHR, "HR");

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashbdActionPerformed
        card.show(pnlContent, "Dashbd");
    }//GEN-LAST:event_btnDashbdActionPerformed

    private void btnAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointActionPerformed
        card.show(pnlContent, "Appoint");

    }//GEN-LAST:event_btnAppointActionPerformed

    private void btnStudsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudsActionPerformed
        card.show(pnlContent, "Studs");

    }//GEN-LAST:event_btnStudsActionPerformed

    private void btnHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHRActionPerformed
        card.show(pnlContent, "HR");
    }//GEN-LAST:event_btnHRActionPerformed

    private void btnHRsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHRsActionPerformed
        card.show(pnlContent, "HR");
    }//GEN-LAST:event_btnHRsActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        new Add_Students().setVisible(true);
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnApptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApptActionPerformed
        card.show(pnlContent, "Appoint");
    }//GEN-LAST:event_btnApptActionPerformed

    private void btnAddStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudActionPerformed
        card.show(pnlContent, "Studs");
        javax.swing.JOptionPane.showMessageDialog(this,
            "Add Student Button Clicked");
    }//GEN-LAST:event_btnAddStudActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        card.show(pnlContent, "Studs");

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAppActionPerformed

    }//GEN-LAST:event_btnDeleteAppActionPerformed

    private void btnCStsAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCStsAppActionPerformed

    }//GEN-LAST:event_btnCStsAppActionPerformed

    private void btnOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOUTActionPerformed
        dispose();
        new LogIn_SignUp().setVisible(true);
    }//GEN-LAST:event_btnOUTActionPerformed

    private void btnAddAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAppointActionPerformed
        Add_Appointment appointment = new Add_Appointment(this);

        appointment.setVisible(true);
    }//GEN-LAST:event_btnAddAppointActionPerformed

    private void btnAddHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHRActionPerformed
        new Add_HealthHistory().setVisible(true);
    }//GEN-LAST:event_btnAddHRActionPerformed

    private void btnDeleteStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudActionPerformed

    }//GEN-LAST:event_btnDeleteStudActionPerformed

    private void btnVDtlsAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVDtlsAppActionPerformed

    }//GEN-LAST:event_btnVDtlsAppActionPerformed

    private void btnEditAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAppActionPerformed

    }//GEN-LAST:event_btnEditAppActionPerformed

    private void btnBookAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAppActionPerformed

    }//GEN-LAST:event_btnBookAppActionPerformed

    private void btnEditStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudActionPerformed

    }//GEN-LAST:event_btnEditStudActionPerformed

    private void btnProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfActionPerformed

    }//GEN-LAST:event_btnProfActionPerformed

    private void btnDeleteHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHRActionPerformed

    }//GEN-LAST:event_btnDeleteHRActionPerformed

    private void btnVWHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVWHRActionPerformed

    }//GEN-LAST:event_btnVWHRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Clinic_Appointment_System().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAppoint;
    private javax.swing.JButton btnAddAppoint;
    private javax.swing.JButton btnAddHR;
    private javax.swing.JButton btnAddStud;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAppoint;
    private javax.swing.JButton btnAppt;
    private javax.swing.JButton btnBookApp;
    private javax.swing.JButton btnCStsApp;
    private javax.swing.JButton btnDashbd;
    private javax.swing.JButton btnDeleteApp;
    private javax.swing.JButton btnDeleteHR;
    private javax.swing.JButton btnDeleteStud;
    private javax.swing.JButton btnEditApp;
    private javax.swing.JButton btnEditStud;
    private javax.swing.JButton btnHR;
    private javax.swing.JButton btnHRs;
    private javax.swing.JButton btnOUT;
    private javax.swing.JButton btnProf;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnStuds;
    private javax.swing.JButton btnVDtlsApp;
    private javax.swing.JButton btnVWHR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel pnlAppoint;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlDashbd;
    private javax.swing.JPanel pnlHR;
    private javax.swing.JPanel pnlStuds;
    // End of variables declaration//GEN-END:variables
}
